### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by duartealexf** [justinkenel/js-sql-parse#1]
Hi Justin. Great job on starting this SQL parser using nearley... it's pretty much the only SQL parser that I've found in the internet based on a parser that supports left-recursion.

I see the last commit was done about 6 months ago... and that there are still many features to be developed (I just tried to parse a CREATE TABLE statement, which apparently was not supported).

This project has pretty much all potential to be actually the only (and decent) JS-based SQL parser.

What is on your mind about this project? Is it stopped? Paused? Are you planning on keep on developing it? What are the next features you have in mind? Are you looking for any contributors?

Cheers.

**Comment by justinkenel** [comment]
Hey @duartealexf I just saw this - it's limping along, I'm mostly adding support as I need it for work projects. If you're at all interested in contributing, feel free to shoot me a PR.

**Comment by duartealexf** [comment]
Hi @justinkenel thanks for replying.
Since i commented, I created this package: https://www.npmjs.com/package/sql-ddl-to-json-schema
It parses SQL DDL statements and transforms to JSON with all the tables definitions. Although full conversion of SQL DDL to JSON Schema form is still WIP, it already converts to a compact form.
Cheers.
