### ISSUE TITLE
nearley supports :i for case insensitivity

### ISSUE THREAD

**Issue by joereynolds** [justinkenel/js-sql-parse#6]
From looking at the code there's a lot of places where code like this

https://github.com/justinkenel/js-sql-parse/blob/5f010925f0f31bda75254f8bbe241c410ed1c82a/sql.ne#L458

Or this

```
ON -> [Oo] [Nn]
OR -> [Oo] [Rr]
ORDER -> [Oo] [Rr] [Dd] [Ee] [Rr]
```

Can be simplified to

```
ON -> "ON"i
OR -> "OR"i
ORDER -> "ORDER"i
```

`:i` means to treat it as case insensitive.

Nice project btw. I came across while looking for resources about nearley and SQL. Is it still active?

**Comment by justinkenel** [comment]
A couple of projects I'm working on for work use it, but I only build out features when it's necessary for that.

It was written before Nearley had `"..."i` support - if you'd like to update it feel free to submit a PR!
